In [1]:
import pandas as pd

In [23]:
iee = pd.read_csv("../exports/export2025.12.10-17.08.03.csv")
scholar = pd.read_csv("../exports/google-scholar.csv", sep=";")
scopus = pd.read_csv("../exports/scopus_export_Dec_10-2025_1ba3c940-0bdc-494a-bee4-d98e57b428f5.csv")
snowball = pd.read_csv('../exports/snowballing.csv')

In [9]:
iee

,Document Title,Authors,Author Affiliations,Publication Title,Date Added To Xplore,Publication Year,Volume,Issue,Start Page,End Page,...,Mesh_Terms,Article Citation Count,Patent Citation Count,Reference Count,License,Online Date,Issue Date,Meeting Date,Publisher,Document Identifier
0,A Simple Approach to Balance Task Loss in Mult...,S. Liang; C. Deng; Y. Zhang,Department of Computer Science and Engineering...,2021 IEEE International Conference on Big Data...,13 Jan 2022,2021,NaN,NaN,812,823,...,NaN,1.0,NaN,115.0,IEEE,13 Jan 2022,NaN,NaN,IEEE,IEEE Conferences
1,Early Lane Change Prediction for Automated Dri...,S. Mozaffari; E. Arnold; M. Dianati; S. Fallah,"Warwick Manufacturing Group, University of War...",IEEE Transactions on Intelligent Vehicles,25 Oct 2022,2022,7,3.0,758,770,...,NaN,57.0,NaN,44.0,IEEE,23 Mar 2022,NaN,NaN,IEEE,IEEE Journals
2,Comparison of Loss Function Weighting Methods ...,Y. Setiyadi; J. Santoso; K. Surendro,School of Electrical Engineering and Informati...,2024 Ninth International Conference on Informa...,15 Apr 2025,2024,NaN,NaN,1,6,...,NaN,NaN,NaN,26.0,IEEE,15 Apr 2025,NaN,NaN,IEEE,IEEE Conferences
3,Curriculum-Based Asymmetric Multi-Task Reinfor...,H. Huang; D. Ye; L. Shen; W. Liu,"Nanyang Technological University, Singapore; T...",IEEE Transactions on Pattern Analysis and Mach...,5 May 2023,2023,45,6.0,7258,7269,...,NaN,13.0,NaN,40.0,IEEE,23 Nov 2022,NaN,NaN,IEEE,IEEE Journals
4,Adaptive Data and Task Joint Scheduling for Mu...,Z. Liu; H. Chai; C. Li; L. Wang; Q. Liao,"Harbin Institute of Technology (Shenzhen), She...",2025 IEEE 41st International Conference on Dat...,20 Aug 2025,2025,NaN,NaN,2038,2051,...,NaN,NaN,NaN,65.0,IEEE,20 Aug 2025,NaN,NaN,IEEE,IEEE Conferences
5,Hierarchical Curriculum Learning for Dysarthri...,I. -T. Hsieh; C. -H. Wu,Graduate Program of Multimedia Systems and Int...,"IEEE Transactions on Audio, Speech and Languag...",21 Aug 2025,2025,33,NaN,3553,3567,...,NaN,NaN,NaN,59.0,IEEE,11 Aug 2025,NaN,NaN,IEEE,IEEE Journals
6,Revisiting Fairness in Multitask Learning: A P...,X. Qin; X. Wang; J. Yan,School of Computer Science & School of Artific...,2025 IEEE/CVF Conference on Computer Vision an...,13 Aug 2025,2025,NaN,NaN,20492,20501,...,NaN,NaN,NaN,43.0,IEEE,13 Aug 2025,NaN,NaN,IEEE,IEEE Conferences
7,Calculation of Optimized Pulse Patterns for El...,L. Hölsch; D. Wiechmann; O. Schweins; O. Walls...,"Chair of Interconnected Automation Systems, Un...",2025 IEEE International Electric Machines & Dr...,4 Jul 2025,2025,NaN,NaN,922,928,...,NaN,NaN,NaN,23.0,IEEE,4 Jul 2025,NaN,NaN,IEEE,IEEE Conferences
8,Adaptive Weighting Based Metal Artifact Reduct...,H. Wang; Y. Wu; Y. Wang; D. Wei; X. Wu; J. Ma;...,"Jarvis Research Center, Tencent YouTu Lab, She...",IEEE Transactions on Medical Imaging,4 Jun 2025,2025,44,6.0,2408,2423,...,"Artifacts;Tomography, X-Ray Computed;Humans;Me...",NaN,NaN,56.0,IEEE,13 Feb 2025,NaN,NaN,IEEE,IEEE Journals
9,Wireless Capsule Endoscopy Diagnosis Using Pro...,X. Li; Q. Wu; Y. Chen; K. Wu; L. Meng,"School of Management, Huazhong University of S...",IEEE Transactions on Automation Science and En...,29 Apr 2025,2025,22,NaN,14260,14271,...,NaN,NaN,NaN,60.0,IEEE,8 Apr 2025,NaN,NaN,IEEE,IEEE Journals
10,Multi-Task Convolutional Neural Network for Po...,X. Yin; X. Liu,Department of Computer Science and Engineering...,IEEE Transactions on Image Processing,28 Nov 2017,2018,27,2.0,964,975,...,"Algorithms;Biometric Identification;Databases,...",244.0,1.0,67.0,IEEE,23 Oct 2017,NaN,NaN,IEEE,IEEE Journals
11,Multi-objective Memetic Algorithm with Adaptiv...,P. Kadlec; M. Capek,"Brno University of Technology, Brno, Czech Rep...",IEEE Transactions on Antennas and Propagation,NaN,2025,PP,99.0,1,1,...,NaN,NaN,NaN,NaN,IEEE,8 Jul 2025,NaN,NaN,IEEE,IEEE Early Access Articles
12,Joint Modeling for ASR Correction and Dialog S...,D. Wang; T. Zhang; C. Yuan; X. Wang,Beijing University of Posts and Telecommunicat...,ICASSP 2023 - 2023 IEEE International Conferen...,5 May 2023,2023,NaN,NaN,1,5,...,NaN,NaN,NaN,16.0,IEEE,5 May 2023,NaN,NaN,IEEE,IEEE Conferences
13,Data vs. Physics: The Apparent Pareto Front of...,F. M. Rohrhofer; S. Posch; C. Gößnitzer; B. C....,"Know-Center GmbH, Research Center for Data-Dri...",IEEE Access,18 Aug 2023,2023,11,NaN,86252,86261,...,NaN,22.0,NaN,36.0,CCBY,7 Aug 2023,NaN,NaN,IEEE,IEEE Journals
14,DAO to HANOI via DeSci: AI Paradigm Shifts fro...,Q. Miao; W. Zheng; Y. Lv; M. Huang; W. Ding; F...,"School of Artificial Intelligence, University ...",IEEE/CAA Journal of Automatica Sinica,28 Mar 2023,2023,10,4.0,877,897,...,NaN,65.0,NaN,73.0,NaN,28 Mar 2023,NaN,NaN,IEEE,IEEE Journals
15,Acoustic Prompt Tuning: Empowering Large Langu...,J. Liang; X. Liu; W. Wang; M. D. Plumbley; H. ...,"Centre for Digital Music (C4DM), Queen Mary Un...","IEEE Transactions on Audio, Speech and Languag...",26 Feb 2025,2025,33,NaN,949,961,...,NaN,2.0,NaN,57.0,IEEE,24 Jan 2025,NaN,NaN,IEEE,IEEE Journals
16,How Simulation Helps Autonomous Driving: A Sur...,X. Hu; S. Li; T. Huang; B. Tang; R. Huai; L. Chen,"School of Artificial Intelligence, Hubei Unive...",IEEE Transactions on Intelligent Vehicles,22 Feb 2024,2024,9,1.0,593,612,...,NaN,71.0,NaN,146.0,IEEE,7 Sep 2023,NaN,NaN,IEEE,IEEE Journals
17,Closed-Loop Control of Droplet Quality Based o...,Y. Shen; H. Zhan; Y. Zhang; Y. Zhang; S. Tang;...,"College of Mechanical Engineering, Zhejiang Un...",IEEE Access,27 Aug 2025,2025,13,NaN,148060,148073,...,NaN,NaN,NaN,35.0,CCBY,5 Aug 2025,NaN,NaN,IEEE,IEEE Journals
18,Loss Balance Aware Algorithms for Single Image...,R. Chen; S. Qiao; Y. Li; Y. Fan,"College of Information Science and Technology,...",IEEE Transactions on Consumer Electronics,17 Jun 2025,2025,71,1.0,260,272,...,NaN,NaN,NaN,35.0,IEEE,27 Jan 2025,NaN,NaN,IEEE,IEEE Journals
19,Blind Image Quality Assessment via Vision-Lang...,W. Zhang; G. Zhai; Y. Wei; X. Yang; K. Ma,"MoE Key Lab of Artificial Intelligence, AI Ins...",2023 IEEE/CVF Conference on Computer Vision an...,22 Aug 2023,2023,NaN,NaN,14071,14081,...,NaN,182.0,NaN,80.0,IEEE,22 Aug 2023,NaN,NaN,IEEE,IEEE Conferences

In [10]:
scholar

                                                Title
0   MTL-BERT: A Multi-Task Learning Framework for ...
1   SPC: Selective Patches Consistency for Cross-D...
2   Socialized Coevolution: Advancing a Better Wor...
3   Task-adaptive debiasing with SCM for sentiment...
4   M2-reasoning: Empowering mllms with unified ge...
..                                                ...
68  Beyond Tokens: Introducing Large Semiosis Mode...
69  Knowledge distillation meets open-set semi-sup...
70                              Procedural Strategies
71  Reinforcement Learning for Autonomous Mobility...
72  Platform for orchestrating a scalable, privacy...

[73 rows x 1 columns]

In [ ]:
jscopus

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,Page end,Cited by,DOI,Link,Document Type,Publication Stage,Open Access,Source,EID
0,"Guo, Y.; Ai, X.; Guo, M.; Cheng, S.","Guo, Yanjun (57330698300); Ai, Xinbo (55813316...",57330698300; 55813316100; 60124349500; 6007702...,Automatic perception of potential safety hazar...,2026,Advanced Engineering Informatics,69,NaN,103919.0,NaN,NaN,0,10.1016/j.aei.2025.103919,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-105017736653
1,"Atamni, N.; Madi, B.; Bordman, S.; Vasyutinsky...","Atamni, Nour (58558005100); Madi, Boraq (57219...",58558005100; 57219761909; 60112510200; 5721990...,Multi-task Learning for Hebrew Paleography: Sc...,2026,Lecture Notes in Computer Science,16027 LNCS,NaN,NaN,79.0,97.0,0,10.1007/978-3-032-04630-7_5,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-105016904249
2,"Dagnaw, G.H.; Zhu, Y.; Maqsood, M.H.; Yin, X.;...","Dagnaw, Getamesay Haile (58754640600); Zhu, Ya...",58754640600; 57192103810; 57351290400; 5719210...,Explainable multimodal hematology analysis for...,2025,Computers in Biology and Medicine,196,NaN,110734.0,NaN,NaN,0,10.1016/j.compbiomed.2025.110734,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-105012229178
3,"Yuan, L.; Zhou, H.-B.; Li, J.-Y.; Liu, L.; Gu,...","Yuan, Li (8452570000); Zhou, Hebin (5991880770...",8452570000; 59918807700; 27170441000; 57930576...,Symmetry Alignment–Feature Interaction Network...,2025,Symmetry,17,5.0,654.0,NaN,NaN,1,10.3390/sym17050654,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-105006819963
4,"Kadlec, P.; Čapek, M.","Kadlec, Petr (55628590839); Čapek, Miloslav (2...",55628590839; 24824101600,Multi-objective Memetic Algorithm with Adaptiv...,2025,IEEE Transactions on Antennas and Propagation,NaN,NaN,NaN,NaN,NaN,1,10.1109/TAP.2025.3584518,https://www.scopus.com/inward/record.uri?eid=2...,Article,aip,NaN,Scopus,2-s2.0-105010344820
5,"Zou, M.; Yu, B.; Zhan, Y.; Lyu, S.; Ma, K.","Zou, Mian (57221976157); Yu, Baosheng (5719211...",57221976157; 57192112952; 56100491900; 8727557...,Semantics-Oriented Multitask Learning for Deep...,2025,IEEE Transactions on Circuits and Systems for ...,35,10.0,NaN,9950.0,9963.0,1,10.1109/TCSVT.2025.3572508,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-105006001564
6,"Setiyadi, Y.; Santoso, J.; Surendro, K.","Setiyadi, Yaya (56532509700); Santoso, Judhi (...",56532509700; 53264786200; 6507613469,Comparison of Loss Function Weighting Methods ...,2024,NaN,NaN,NaN,NaN,NaN,NaN,0,10.1109/ICIC64337.2024.10957579,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-105004579467
7,"Wang, D.; Zhang, T.; Yuan, C.; Wang, X.","Wang, Deyuan (58706241200); Zhang, Tiantian (5...",58706241200; 58738159200; 37056632700; 3523564...,Joint Modeling for ASR Correction and Dialog S...,2023,"Proceedings - ICASSP, IEEE International Confe...",2023-June,NaN,NaN,NaN,NaN,2,10.1109/ICASSP49357.2023.10095945,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-85177604860
8,"Rohrhofer, F.M.; Posch, S.; Gobnitzer, C.; Gei...","Rohrhofer, Franz M. (57222238812); Posch, Stef...",57222238812; 6602338394; 58558802300; 57195470728,Data vs. Physics: The Apparent Pareto Front of...,2023,IEEE Access,11,NaN,NaN,86252.0,86261.0,17,10.1109/ACCESS.2023.3302892,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85167812124
9,"Mozaffari, S.; Arnold, E.; Dianati, M.; Fallah...","Mozaffari, Sajjad (57219585131); Arnold, Eduar...",57219585131; 57211023741; 8930535800; 57212012224,Early Lane Change Prediction for Automated Dri...,2022,IEEE Transactions on Intelligent Vehicles,7,3.0,NaN,758.0,770.0,63,10.1109/TIV.2022.3161785,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Green Accepted Open Access; G...,Scopus,2-s2.0-85127044415
10,"Hervella, Á.S.; Rouco, J.; Novo, J.; Ortega, M.","Hervella, Alvaro S. (57204014400); Rouco, José...",57204014400; 23475243900; 57695901400; 2447540...,End-to-end multi-task learning for simultaneou...,2022,Applied Soft Computing,116,NaN,108347.0,NaN,NaN,73,10.1016/j.asoc.2021.108347,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Green Accepted Open Access; G...,Scopus,2-s2.0-85122186820
11,"de Lhoneux, M.; Zhang, S.; Sogaard, A.","de Lhoneux, Miryam (57193355196); Zhang, Sheng...",57193355196; 57211157782; 24336006300,Zero-Shot Dependency Parsing with Worst-Case A...,2022,Proceedings of the Annual Meeting of the Assoc...,2,NaN,NaN,578.0,587.0,12,10.18653/v1/2022.acl-short.64,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,All Open Access; Gold Open Access; Green Accep...,Scopus,2-s2.0-85127763115
12,"Chennupati, S.; Sistu, G.; Yogamani, S.; Rawas...","Chennupati, Sumanth Kumar (57194194507); Sistu...",57194194507; 57204978122; 55612733500; 3611707...,AuxNet: Auxiliary tasks enhanced semantic segm...,2019,NaN,5,NaN,NaN,645.0,652.0,27,10.5220/0007684106450652,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,All Open Access; Gold Open Access; Green Accep...,Scopus,2-s2.0-85068514545
13,"Yin, X.; Liu, X.","Yin, Xi (56288395400); Liu, Xiaoming (35793096...",56288395400; 35793096800,Multi-Task Convolutional Neural Network for Po...,2018,IEEE Transactions on Image Processing,27,2.0,8080244.0,964.0,975.0,273,10.1109/TIP.2017.2765830,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Green Accepted Open Access; G...,Scopus,2-s2.0-85032455104
14,"Hassani, K.; Lee, W.-S.","Hassani, Kaveh (36188267400); Lee, Wonsook (57...",36188267400; 57203094498,Multi-objective design of state feedback contr...,2016,Applied Soft Computing,41,NaN,NaN,66.0,76.0,46,10.1016/j.asoc.2015.12.024,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Green Accepted Open Access; G...,Scopus,2-s2.0-84953888885
15,"Izui, K.; Yamada, T.; Nishiwaki, S.; Tanaka, K.","Izui, Kazuhiro (7005455636); Yamada, Takayuki ...",7005455636; 55490858800; 7005352221; 55850702200,Multiobjective optimization using an aggregati...,2015,Structural and Multidisciplinary Optimization,51,1.0,NaN,173.0,182.0,31,10.1007/s00158-014-1125-8,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-84924223375
16,"Izui, K.; Nishiwaki, S.; Yoshimura, M.; Nakamu...","Izui, Kazuhiro (7005455636); Nishiwaki, Shinji...",7005455636; 7005352221; 55040643200; 569842308...,Enhanced multiobjective particle swarm optimiz...,2008,Engineering Optimization,40,9.0,NaN,789.0,804.0,20,10.1080/03052150802046247,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-49749110448

In [21]:
titles = pd.concat([scopus["Source title"], iee["Document Title"], scholar["Title"], snowball["Title"]], ignore_index=True)

In [22]:
titles.sort_values()

17     A Simple Approach to Balance Task Loss in Mult...
110    A Survey of Multi-task Learning in Natural Lan...
57     A Systematic Literature Review on Multimodal A...
47     A lightweight operation mode decision method f...
80            A survey of direct preference optimization
                             ...
126    Visualizing and Understanding Curriculum Learn...
86     When Remote Sensing Meets Foundation Model: A ...
26     Wireless Capsule Endoscopy Diagnosis Using Pro...
6                                                    NaN
12                                                   NaN
Length: 127, dtype: object

In [35]:
cieee = iee[iee["Chosen"]]
cieee

,Document Title,Authors,Author Affiliations,Publication Title,Date Added To Xplore,Publication Year,Volume,Issue,Start Page,End Page,...,Article Citation Count,Patent Citation Count,Reference Count,License,Online Date,Issue Date,Meeting Date,Publisher,Document Identifier,Chosen
3,Curriculum-Based Asymmetric Multi-Task Reinfor...,H. Huang; D. Ye; L. Shen; W. Liu,"Nanyang Technological University, Singapore; T...",IEEE Transactions on Pattern Analysis and Mach...,5 May 2023,2023,45,6.0,7258,7269,...,13.0,NaN,40.0,IEEE,23 Nov 2022,NaN,NaN,IEEE,IEEE Journals,True
5,Hierarchical Curriculum Learning for Dysarthri...,I. -T. Hsieh; C. -H. Wu,Graduate Program of Multimedia Systems and Int...,"IEEE Transactions on Audio, Speech and Languag...",21 Aug 2025,2025,33,NaN,3553,3567,...,NaN,NaN,59.0,IEEE,11 Aug 2025,NaN,NaN,IEEE,IEEE Journals,True
9,Wireless Capsule Endoscopy Diagnosis Using Pro...,X. Li; Q. Wu; Y. Chen; K. Wu; L. Meng,"School of Management, Huazhong University of S...",IEEE Transactions on Automation Science and En...,29 Apr 2025,2025,22,NaN,14260,14271,...,NaN,NaN,60.0,IEEE,8 Apr 2025,NaN,NaN,IEEE,IEEE Journals,True
17,Closed-Loop Control of Droplet Quality Based o...,Y. Shen; H. Zhan; Y. Zhang; Y. Zhang; S. Tang;...,"College of Mechanical Engineering, Zhejiang Un...",IEEE Access,27 Aug 2025,2025,13,NaN,148060,148073,...,NaN,NaN,35.0,CCBY,5 Aug 2025,NaN,NaN,IEEE,IEEE Journals,True

In [33]:
cscopus = scopus[scopus["Chosen"]]
cscopus

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,Page end,Cited by,DOI,Link,Document Type,Publication Stage,Open Access,Source,EID,Chosen
7,"Wang, D.; Zhang, T.; Yuan, C.; Wang, X.","Wang, Deyuan (58706241200); Zhang, Tiantian (5...",58706241200; 58738159200; 37056632700; 3523564...,Joint Modeling for ASR Correction and Dialog S...,2023,"Proceedings - ICASSP, IEEE International Confe...",2023-June,NaN,NaN,NaN,NaN,2,10.1109/ICASSP49357.2023.10095945,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-85177604860,True
9,"Mozaffari, S.; Arnold, E.; Dianati, M.; Fallah...","Mozaffari, Sajjad (57219585131); Arnold, Eduar...",57219585131; 57211023741; 8930535800; 57212012224,Early Lane Change Prediction for Automated Dri...,2022,IEEE Transactions on Intelligent Vehicles,7,3.0,NaN,758.0,770.0,63,10.1109/TIV.2022.3161785,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Green Accepted Open Access; G...,Scopus,2-s2.0-85127044415,True
11,"de Lhoneux, M.; Zhang, S.; Sogaard, A.","de Lhoneux, Miryam (57193355196); Zhang, Sheng...",57193355196; 57211157782; 24336006300,Zero-Shot Dependency Parsing with Worst-Case A...,2022,Proceedings of the Annual Meeting of the Assoc...,2,NaN,NaN,578.0,587.0,12,10.18653/v1/2022.acl-short.64,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,All Open Access; Gold Open Access; Green Accep...,Scopus,2-s2.0-85127763115,True

In [39]:
cscholar = scholar[scholar["Chosen"]]
cscholar

                                                Title  Chosen
0   MTL-BERT: A Multi-Task Learning Framework for ...    True
1   SPC: Selective Patches Consistency for Cross-D...    True
5   REST: Drug-drug interaction prediction via rei...    True
6   Open-ended coordination for multi-agent system...    True
9   Beyond Standard Losses: Redefining Text-to-SQL...    True
10  A lightweight operation mode decision method f...    True
13  Shy-hunyuan-MT at WMT25 General Machine Transl...    True
14  Backpropagation-based Parameter Tuning and Gra...    True
15  LocalGCL: Local-aware Contrastive Learning for...    True
16  Adaptive training distributions with scalable ...    True
17  Vision Large Language Models Are Good Noise Ha...    True
18  Uncertainty-aware evidential fusion-based lear...    True
19  A weighted difference loss approach for enhanc...    True
22                              Modular deep learning    True
24  Reinforced mllm: A survey on rl-based reasonin...    True
25  HAND: Hierarchical Attention Network for Multi...    True
26  Object Segmentation Based on Pseudo Supervisio...    True
28  Feature Based Methods in Domain Adaptation for...    True
29  Detecting Data Deviations in Electronic Health...    True
30  Unlabeled Insight, Labeled Boost: Contrastive ...    True
32  STRIDE: Automating Reward Design, Deep Reinfor...    True
38  Sdat-former++: A foggy scene semantic segmenta...    True
43         A survey of direct preference optimization    True
48  Skill-it! a data-driven skills framework for u...    True
52                                            TMS-GNN    True
54  Timebalance: Temporally-invariant and temporal...    True
56  On the opportunities of green computing: A survey    True
58  Increasing importance of joint analysis of aud...    True
59  Applied Deep Learning for Natural Language Pro...    True
60  Prototype equilibrium network with group emoti...    True
64  On Adversarial Robustness of Deep Learning-bas...    True
69  Knowledge distillation meets open-set semi-sup...    True

In [40]:
ctitles = pd.concat([cscopus["Source title"], cieee["Document Title"], cscholar["Title"], snowball["Title"]], ignore_index=True)
ctitles.sort_values()

39    A Survey of Multi-task Learning in Natural Lan...
12    A lightweight operation mode decision method f...
29           A survey of direct preference optimization
19    A weighted difference loss approach for enhanc...
16    Adaptive training distributions with scalable ...
35    Applied Deep Learning for Natural Language Pro...
14    Backpropagation-based Parameter Tuning and Gra...
11    Beyond Standard Losses: Redefining Text-to-SQL...
6     Closed-Loop Control of Droplet Quality Based o...
40    Competence-based Curriculum Learning for Neura...
41    Curriculum Learning via Transitional Objective...
42                        Curriculum Learning: A Survey
43                                  Curriculum learning
3     Curriculum-Based Asymmetric Multi-Task Reinfor...
25    Detecting Data Deviations in Electronic Health...
44    Efficient Knowledge Distillation via Curriculu...
24    Feature Based Methods in Domain Adaptation for...
45    From Baby Steps to Leapfrog: How “Less is More...
46    GradNorm: Gradient Normalization for Adaptive ...
22    HAND: Hierarchical Attention Network for Multi...
4     Hierarchical Curriculum Learning for Dysarthri...
1             IEEE Transactions on Intelligent Vehicles
34    Increasing importance of joint analysis of aud...
38    Knowledge distillation meets open-set semi-sup...
47    Learning and development in neural networks: t...
48                                  Learning to Execute
49    Learning to Reweight Examples for Robust Deep ...
15    LocalGCL: Local-aware Contrastive Learning for...
7     MTL-BERT: A Multi-Task Learning Framework for ...
50    Meta Learning for Natural Language Processing:...
51           Meta-Learning in Neural Networks: A Survey
52    Meta-learning Approaches for Few-Shot Learning...
53    MetaWeighting: Learning to Weight Tasks in Mul...
20                                Modular deep learning
23    Object Segmentation Based on Pseudo Supervisio...
37    On Adversarial Robustness of Deep Learning-bas...
33    On the opportunities of green computing: A survey
10    Open-ended coordination for multi-agent system...
0     Proceedings - ICASSP, IEEE International Confe...
2     Proceedings of the Annual Meeting of the Assoc...
36    Prototype equilibrium network with group emoti...
9     REST: Drug-drug interaction prediction via rei...
21    Reinforced mllm: A survey on rl-based reasonin...
54    Reverse Curriculum Generation for Reinforcemen...
8     SPC: Selective Patches Consistency for Cross-D...
27    STRIDE: Automating Reward Design, Deep Reinfor...
28    Sdat-former++: A foggy scene semantic segmenta...
13    Shy-hunyuan-MT at WMT25 General Machine Transl...
30    Skill-it! a data-driven skills framework for u...
31                                              TMS-GNN
32    Timebalance: Temporally-invariant and temporal...
18    Uncertainty-aware evidential fusion-based lear...
26    Unlabeled Insight, Labeled Boost: Contrastive ...
17    Vision Large Language Models Are Good Noise Ha...
55    Visualizing and Understanding Curriculum Learn...
5     Wireless Capsule Endoscopy Diagnosis Using Pro...
dtype: object